name: Debug

on:
  workflow_dispatch:

env:
  PR_NUMBER: 23
  RELEASE_TAG_SHA: 4c622f390949baf5e33a9aa8be1606209815ba13
  
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Debug
        run: |
          gh api \
            --method POST \
            /repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews \
            -f commit_id=$RELEASE_TAG_SHA \
            -f body='LGTM!' \
            -f event='APPROVE'
            
          gh api \
            --method PUT \
            /repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/merge
