name: Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Debug
        run: |
          git fetch --unshallow --tags
          git tag
          echo -------------
          git config --global user.email "francois@boostsecurity.io"
          git config --global user.name "fproulx-boostsecurity"
          export RELEASE_BRANCH="release-v0.0.2+$((RANDOM%1000))"
          git switch -c $RELEASE_BRANCH
          git commit --allow-empty -m "Release $RELEASE_BRANCH"
          echo -------------
          git push --set-upstream origin $RELEASE_BRANCH
          echo -------------
          git tag --verbose -f v0.0.2
          echo -------------
          git push --verbose -f origin
