name: Debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          git config --global user.email "francois@boostsecurity.io"
          git config --global user.name "fproulx-boostsecurity"
          export RELEASE_BRANCH="release-v0.0.2+$((RANDOM%1000))"
          git switch -c $RELEASE_BRANCH
          git commit --allow-empty -m "Release $RELEASE_BRANCH"
          git push --set-upstream origin $RELEASE_BRANCH
          echo "-----------------------------"
          git tag
          echo "-----------------------------"
          git tag --verbose -f v0.0.2
          git push --verbose -f origin
